version: "3.8"
services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:v1.1-beta12
    container_name: sing-box
    network_mode: "host"
    volumes:
      - ./config.json:/etc/sing-box/config.json
    restart: unless-stopped
    command: " -c /etc/sing-box/config.json run"
